# Generated by Django 3.0.7 on 2020-07-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_auto_20200704_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
