# Generated by Django 3.0.7 on 2020-07-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_member_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='child',
            field=models.BooleanField(default=False, help_text='For only children'),
        ),
        migrations.AlterField(
            model_name='member',
            name='location',
            field=models.CharField(blank=True, help_text='Auto generated, do not change!', max_length=255, null=True),
        ),
    ]
