# Generated by Django 3.0.7 on 2020-07-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_auto_20200704_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='location',
            field=models.CharField(blank=True, help_text='Town/Residence/House number', max_length=255, null=True),
        ),
    ]
