# Generated by Django 3.0.7 on 2020-07-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_auto_20200704_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='temperature',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
