# Generated by Django 3.0.7 on 2020-07-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_auto_20200705_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
