# Generated by Django 3.0.7 on 2020-07-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0010_auto_20200705_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='service',
            field=models.CharField(choices=[('1', '1st Service'), ('2', '2nd Service'), ('Joint', 'Joint Service')], default='1', max_length=100),
        ),
    ]
